---
- name: Handle the directory creation and/or cleanup
  when: >
    ansibleautomationplatform is defined or
    automationcontroller is defined or
    automationhub is defined or
    eda is defined or
    secrets is defined or
    configmaps is defined or
    operatorgroups is defined or
    subscriptions is defined
  block:
    - name: Empty the generated templates directory, if it exists
      ansible.builtin.file:
        path: "{{ generate_kubemanifests_template_host_dir }}"
        state: absent
      when: generate_kubemanifests_template_empty | bool

    - name: Create the generated templates directory
      ansible.builtin.file:
        mode: '0775'
        path: "{{ generate_kubemanifests_template_host_dir }}"
        state: directory

- name: Handle the crs directory creation
  when: >
    ansibleautomationplatform is defined or
    automationcontroller is defined or
    automationhub is defined or
    eda is defined
  block:
    - name: Create the generated crs directory
      ansible.builtin.file:
        mode: '0775'
        path: "{{ generate_kubemanifests_template_host_dir }}/crs"
        state: directory

- name: Handle the configmaps directory creation
  when: configmaps is defined and configmaps
  block:
    - name: Create the generated configmaps directory
      ansible.builtin.file:
        mode: '0775'
        path: "{{ generate_kubemanifests_template_host_dir }}/configmaps"
        state: directory

- name: Handle the routes directory creation
  when: routes is defined and routes
  block:
    - name: Create the generated routes directory
      ansible.builtin.file:
        mode: '0775'
        path: "{{ generate_kubemanifests_template_host_dir }}/routes"
        state: directory

- name: Handle the secrets directory creation
  when: secrets is defined and secrets
  block:
    - name: Create the generated secrets directory
      ansible.builtin.file:
        mode: '0775'
        path: "{{ generate_kubemanifests_template_host_dir }}/secrets"
        state: directory

- name: Handle the subscriptions directory creation
  when: subscriptions is defined and subscriptions
  block:
    - name: Create the generated subscriptions directory
      ansible.builtin.file:
        mode: '0775'
        path: "{{ generate_kubemanifests_template_group_dir }}/subscriptions"
        state: directory

- name: Handle the operatorgroups directory creation
  when: operatorgroups is defined and operatorgroups
  block:
    - name: Create the generated operatorgroups directory
      ansible.builtin.file:
        mode: '0775'
        path: "{{ generate_kubemanifests_template_group_dir }}/operatorgroups"
        state: directory

- name: Handle the pvcs directory creation
  when: pvcs is defined and pvcs
  block:
    - name: Create the generated pvcs directory
      ansible.builtin.file:
        mode: '0775'
        path: "{{ generate_kubemanifests_template_host_dir }}/pvcs"
        state: directory

- name: Template ansibleautomationplatform.yml
  ansible.builtin.copy:
    content: >
      {{
        lookup('ansible.builtin.template', generate_kubemanifests_template_file_ansibleautomationplatform) |
        from_yaml |
        combine(ansibleautomationplatform, recursive=true) |
        to_nice_yaml(2)
      }}
    dest: "{{ generate_kubemanifests_template_host_dir }}/crs/ansibleautomationplatform.yml"
    mode: '0644'
  when: ansibleautomationplatform is defined and ansibleautomationplatform

- name: Template automationcontroller.yml
  ansible.builtin.copy:
    content: >
      {{
        lookup('ansible.builtin.template', generate_kubemanifests_template_file_automationcontroller) |
        from_yaml |
        combine(automationcontroller, recursive=true) |
        to_nice_yaml(2)
      }}
    dest: "{{ generate_kubemanifests_template_host_dir }}/crs/automationcontroller.yml"
    mode: '0644'
  when: automationcontroller is defined and automationcontroller

- name: Template automationhub.yml
  ansible.builtin.copy:
    content: >
      {{
        lookup('ansible.builtin.template', generate_kubemanifests_template_file_automationhub) |
        from_yaml |
        combine(automationhub, recursive=true) |
        to_nice_yaml(2)
      }}
    dest: "{{ generate_kubemanifests_template_host_dir }}/crs/automationhub.yml"
    mode: '0644'
  when: automationhub is defined and automationhub

- name: Template eda.yml
  ansible.builtin.copy:
    content: >
      {{
        lookup('ansible.builtin.template', generate_kubemanifests_template_file_eda) |
        from_yaml |
        combine(eda, recursive=true) |
        to_nice_yaml(2)
      }}
    dest: "{{ generate_kubemanifests_template_host_dir }}/crs/eda.yml"
    mode: '0644'
  when: eda is defined and eda

- name: Template configmaps
  ansible.builtin.copy:
    content: >
      {{
        lookup('ansible.builtin.template', generate_kubemanifests_template_file_configmap) |
        from_yaml |
        to_nice_yaml(indent=2, sort_keys=false)
      }}
    dest: "{{ generate_kubemanifests_template_host_dir }}/configmaps/{{ item.metadata.name }}.yml"
    mode: '0644'
  loop: "{{ configmaps }}"
  when: configmaps is defined and configmaps

- name: Template pvcs
  ansible.builtin.copy:
    content: >
      {{
        lookup('ansible.builtin.template', generate_kubemanifests_template_file_pvc) |
        from_yaml |
        combine(item, recursive=true) |
        to_nice_yaml(indent=2, sort_keys=false)
      }}
    dest: "{{ generate_kubemanifests_template_host_dir }}/pvcs/{{ item.metadata.name }}.yml"
    mode: '0644'
  loop: "{{ pvcs }}"
  when: pvcs is defined and pvcs

- name: Template routes
  ansible.builtin.copy:
    content: >
      {{
        lookup('ansible.builtin.template', generate_kubemanifests_template_file_route) |
        from_yaml |
        combine(item, recursive=true) |
        to_nice_yaml(indent=2, sort_keys=false)
      }}
    dest: "{{ generate_kubemanifests_template_host_dir }}/routes/{{ item.metadata.name }}.yml"
    mode: '0644'
  loop: "{{ routes }}"
  when: routes is defined and routes

- name: Template secrets
  ansible.builtin.copy:
    content: >
      {{
        lookup('ansible.builtin.template', generate_kubemanifests_template_file_secret) |
        from_yaml |
        to_nice_yaml(indent=2, sort_keys=false)
      }}
    dest: "{{ generate_kubemanifests_template_host_dir }}/secrets/{{ item.metadata.name }}.yml"
    mode: '0644'
  loop: "{{ secrets }}"
  no_log: true
  when: secrets is defined and secrets

- name: Template subscriptions
  ansible.builtin.copy:
    content: >
      {{
        lookup('ansible.builtin.template', generate_kubemanifests_template_file_subscription) |
        from_yaml |
        combine(item, recursive=true) |
        to_nice_yaml(indent=2, sort_keys=false)
      }}
    dest: "{{ generate_kubemanifests_template_group_dir }}/subscriptions/{{ item.metadata.name }}.yml"
    mode: '0644'
  loop: "{{ subscriptions }}"
  when: subscriptions is defined and subscriptions

- name: Template operatorgroups
  ansible.builtin.copy:
    content: >
      {{
        lookup('ansible.builtin.template', generate_kubemanifests_template_file_operatorgroup) |
        from_yaml |
        combine(item, recursive=true) |
        to_nice_yaml(indent=2, sort_keys=false)
      }}
    dest: "{{ generate_kubemanifests_template_group_dir }}/operatorgroups/{{ item.metadata.name }}.yml"
    mode: '0644'
  loop: "{{ operatorgroups }}"
  when: operatorgroups is defined and operatorgroups
